functionsDirectory = "D:\\Rudhi\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "D:\\Rudhi\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "D:\\Rudhi\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]